config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:new, :create, :show, :update]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
  validates :task_name,presence: true,length:{in:1..140}
  validates :task_content,presence: true,length:{in:1..140}

  enum priority:{
    低: 1,
    中: 2,
    高: 3
  }


  scope :recent_order, -> {order(created_at: :desc)}
  scope :limit_order_desc, -> {order(limit: :desc)}
  scope :limit_order_asc, -> {order(limit: :asc)}
  scope :priority_order_desc, -> {order(priority: :desc)}
  scope :priority_order_asc, -> {order(priority: :asc)}

  def self.name_search(search)
    where("task_name LIKE ?", "%#{search}%")
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks=current_user.tasks.recent_order.page(params[:page])
  end
  def show
    @task=Task.find(params[:id])
  end

  def new
    @task=Task.new
  end

  def create
    @task=Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to tasks_path, notice: "タスクを作成しました！"
    else
      render :new
    end
  end

  def edit
    @task=Task.find(params[:id])
  end

  def update
    @task=Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task=Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました！"
  end

  def search
    @tasks=current_user.tasks.recent_order.page(params[:page])
    if params[:task].present?
      if params[:task][:task_name].present? && params[:task][:status].present? && params[:task][:label_id].present?
        @task_id=Labelling.where(label_id: params[:task][:label_id]).pluck(:task_id)
        @tasks=current_user.tasks.where(status: params[:task][:status]).name_search(params[:task][:task_name]).where(id: @task_id).page(params[:page])
        limit_order_select_and
        priority_order_and
        render :index
        return
      elsif params[:task][:task_name].present? && params[:task][:label_id].present?
        @task_id=Labelling.where(label_id: params[:task][:label_id]).pluck(:task_id)
        @tasks=current_user.tasks.name_search(params[:task][:task_name]).where(id: @task_id).page(params[:page])
        limit_order_select_and
        priority_order_and
        render :index
        return
      elsif params[:task][:status].present? && params[:task][:label_id].present?
        @task_id=Labelling.where(label_id: params[:task][:label_id]).pluck(:task_id)
        @tasks=current_user.tasks.where(status: params[:task][:status]).where(id: @task_id).page(params[:page])
        limit_order_select_and
        priority_order_and
        render :index
        return
      elsif params[:task][:status].present? && params[:task][:task_name].present?
        @tasks=current_user.tasks.where(status: params[:task][:status]).name_search(params[:task][:task_name]).page(params[:page])
        limit_order_select_and
        priority_order_and
        render :index
        return
      elsif params[:task][:status].present?
        @tasks=current_user.tasks.where(status: params[:task][:status]).page(params[:page])
        limit_order_select_and
        priority_order_and
        render :index
        return
      elsif params[:task][:task_name].present?
        @tasks=current_user.tasks.name_search(params[:task][:task_name]).page(params[:page])
        limit_order_select_and
        priority_order_and
        render :index
        return
      elsif params[:task][:label_id].present?
        @task_id=Labelling.where(label_id: params[:task][:label_id]).pluck(:task_id)
        @tasks=current_user.tasks.where(id: @task_id).page(params[:page])
        limit_order_select_and
        priority_order_and
        render :index
        return
      end
    end
      limit_order_select_only
      priority_order_only
      render :index
  end
  

  private

  def task_params
    params.require(:task).permit(:task_name,:task_content,:limit,:status,:priority,:user_id,label_ids: [])
  end

  def limit_order_select_and
    if params[:task][:limit_select]=="昇順"
      @tasks = @tasks.limit_order_asc.page(params[:page])
    elsif params[:task][:limit_select]=="降順"
      @tasks = @tasks.limit_order_desc.page(params[:page])
    end
  end

  def limit_order_select_only
    if params[:task][:limit_select]=="昇順"
      @tasks = current_user.tasks.limit_order_asc.page(params[:page])
    elsif params[:task][:limit_select]=="降順"
      @tasks = current_user.tasks.limit_order_desc.page(params[:page])
    end
  end

  def priority_order_and
    if params[:task][:priority] == "優先▼"
      @tasks = @tasks.priority_order_desc.page(params[:page])
    elsif params[:task][:priority] == "優先▲"
      @tasks = @tasks.priority_order_asc.page(params[:page])
    end
  end

  def priority_order_only
    if params[:task][:priority] == "優先▼"
      @tasks = current_user.tasks.priority_order_desc.page(params[:page])
    elsif params[:task][:priority] == "優先▲"
      @tasks = current_user.tasks.priority_order_asc.page(params[:page])
    end
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>投稿内容を記入してください</p>
  <div class="form-group">
    <%= form.label :task_name,"タスク名" %>
    <%= form.text_field :task_name %>
  </div>
  <div class="form-group">
    <%= form.label :task_content,"内容" %>
    <%= form.text_field :task_content %>
  </div>
  <div class="form-group">
    <%= form.label :limit,"期日" %>
    <%= form.date_field :limit %>
  </div>
  <div class="form-group">
    <%= form.label :status,"ステータス" %>
    <%= form.select :status,["未着手","着手中","完了"] %>
  </div>
  <div class="form-group">
    <%= form.label :priority,"優先度" %>
    <%= form.select :priority,Task.priorities.keys.to_a %>
  </div>
  <div class="form-group">
    <%= form.label :label_name,"タグ" %>
    <%= form.collection_check_boxes( :label_ids, Label.all, :id, :label_name)%>
  </div>
  <%= form.submit "タスク作成" %>
<% end %>
<div class="task_index">
  <%= link_to "タスク一覧画面にもどる", tasks_path,class: "btn btn-primary" %>
</div>
<style>
.task_index{
  padding-top:10px;
}
p{
  padding-right:10px;
}
</style>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>
<%=render 'form'%>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<p><%=notice%></p>
<%= form_with(url: search_tasks_path,local: true, method: :get,scope: :task) do |form| %>
  <div class="form-group">
    <%=form.label :task_name, "キーワード"%>
    <%=form.text_field :task_name,placeholder: "キーワードを入力"%>
  </div>

  <div class="form-group">
    <%=form.label :status, "ステータス"%>
    <%= form.select :status,["未着手","着手中","完了"],include_blank: true %>
  </div>

  <div class="form-group">
    <%=form.label :limit, "期限"%>
    <%= form.select :limit_select,["なし","昇順","降順"],include_blank: true%>
  </div>

  <div class="form-group">
    <%= form.label :priority, "優先度"%>
    <%= form.select :priority,["優先▼","優先▲"],include_blank: true %>
  </div>
  <div class="form-group">
    <%=form.label :label_name, "タグ"%>
    <%= form.select :label_id, Label.all.collect{|p|[p.label_name, p.id]},include_blank: true, class: 'form-control mb-3' %>
  </div>
  <div class="form-group">
    <%= form.submit "検索",class: "search-btn" %>
    <%=link_to "タスク作成",new_task_path,class: "btn btn-primary"%>
  </div>
<% end %>
<table class="table table-striped">
  <tr>
    <th>ユーザー名</th>
    <th>タスク名</th>
    <th>内容</th>
    <th>日付</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先度</th>
    <th>タグ</th>
    <th>詳細</th>
    <th>編集</th>
    <th>削除</th>
  </tr>

<% @tasks.each do |task| %>
  <tr class="task_all">
    <td><%= task.user.name %></td>
    <td><%= task.task_name %></td>
    <td><%= task.task_content %></td>
    <td><%= l task.created_at, format: :short %></td>
    <td><%= l task.limit, format: :long %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td>
      <% task.labels.pluck(:label_name).each do |label| %>
        <label class="btn btn-secondary"><%= label %></label>
      <% end %>
    </td>
    <td><%= link_to '詳細を確認する', task_path(task.id),class:"btn btn-outline-success" %></td>
    <td><%= link_to "タスクを編集する", edit_task_path(task.id), class:"btn btn-outline-danger"%></td>
    <td><%= link_to "タスクを削除する", task_path(task.id), method: :delete,data: { confirm: '本当に削除していいですか？' } ,class:"btn btn-outline-warning" %></td>
  </tr>
<% end %>
</table>

<%= paginate @tasks%>

<style>
h1{
  text-align:center;
}
th {
  text-align:center;
}
td {
  text-align:center;
}
table{
  border:solid 1px #c0c0c0;
}
.pagination {
  justify-content: center;
}
.form-group{
  float:left;
  padding: 0 30px;
}
.btn-primary{
  margin-left:20px
}
</style>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>
<%=render 'form'%>

app/views/tasks/show.html.erb
<h1>タスク詳細画面</h1>
<p>タスク名: <%= @task.task_name %></p>
<p>内容: <%= @task.task_content %></p>
<p>終了期限：<%= @task.limit %></p>
<p>ステータス：<%= @task.status %></p>
<p>優先順位：<%= @task.priority %></p>
<p>
  タグ：<% @task.labels.pluck(:label_name).each do |label| %>
          <label class="btn btn-secondary"><%= label %></label>
        <% end %>
</p>
<%=link_to "タスク一覧に戻る",tasks_path%>