config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :tasks do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:new, :create, :show, :update]
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyouKadaiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    header {
      background-color: #c0c0c0;
      height:80px;
    }
    .login{
      font-size:30px;
      padding:20px;
      color:#fff;
    }
    </style>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user.id),class: "login" %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete,class: "login" %>
        <%=link_to "タスク作成",new_task_path,class: "login"%>
        <%= link_to "タスク一覧", tasks_path,class: "login" %>
        <%=link_to "プロフィール",user_path(current_user.id),class:"login"%>
        <%=link_to "管理者画面",admin_users_path,class:"login" if admin?%>
      <% else %>
        <%= link_to "Sign up", new_user_path,class: "login" %>
        <%= link_to "Login", new_session_path,class: "login" %>
      <% end %>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>